server {
    listen 80;
    client_max_body_size 20m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location /api/ {
        set $up_backend http://backend:8000;
        proxy_pass $up_backend$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 3600s;
    }

    location /admin/ {
        set $up_backend http://backend:8000;
        proxy_pass $up_backend$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        set $up_backend http://backend:8000;
        proxy_pass $up_backend$request_uri;
        proxy_set_header Host $host;
    }

    location / {
        set $up_frontend http://frontend:3000;
        proxy_pass $up_frontend$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
